
name: Publish NPM Package

on:
  push:
    tags:
      -  v*
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write # required to get token for "npm provenance" and to dispatch event
    steps:
      - name: Set VERSION
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/v*}" >> $GITHUB_ENV
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: 📦 Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  githubRelease:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # create the GH release
    steps:
      - uses: actions/checkout@v5
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
