
name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'New version type [new-version | major | minor | patch]'
        required: true
        default: 'patch'
jobs:
  bumpVersion:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: 🔧 Git Setup
        uses: bonitasoft/git-setup-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
      - run: |
          echo "New version type: ${{ inputs.type }}"
      - uses: actions/checkout@v5
        with:
          # Use a PAT to ensure workflow run are triggered after git push
          token: ${{ secrets.BONITA_CI_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Checkout main
        run: git checkout main && git pull --tags
      - name: Bump Version
        run: |
          npm version ${{ inputs.type }} --no-commit-hooks --message "chore(release): %s"
      - name: Push Version
        run: git push && git push --tags
